- import_tasks: common.yml

- import_tasks: centos-7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- import_tasks: centos-6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
