server{
    listen 80;
    server_name m.poizon.com;

    location / {
        set $group sns;
        set $project community_api_service;
        set $upstream_name dw-prd-$group-$project;
        add_header upstream_name $upstream_name;
        proxy_pass http://$upstream_name;
    }
}
