user ops; # nginx启动用户
worker_processes auto; # 打开进程数等于CPU核数
worker_cpu_affinity auto; # cpu亲和
worker_rlimit_nofile  65535;
error_log  /var/log/nginx/error.log error;
pid        /var/run/nginx.pid;

events {
    use epoll; # io多路复用
    worker_connections 10240;# 每一个worker进程能够处理多少连接
}

http {
    include         /etc/nginx/mime.types;
    default_type  application/octet-stream;
    charset utf-8;

    log_format main '$time_iso8601\t$uri\t$args\t$status\t$request_time\t$upstream_response_time\t$remote_addr\t$uid_got$uid_set\t'
                    '$http_host\t$request_method\t$body_bytes_sent\t$http_referer\t$http_user_agent\t$upstream_addr\t$server_protocol\t'
                    '$http_x_forwarded_for\t$http_cookie\t$http_uuid\t$server_port';

    access_log /var/log/nginx/access-$host.log main;

    server_tokens off; # 隐藏nginx版本号
    keepalive_timeout  65;
    keepalive_requests 8192;
    sendfile           on; # 立即将数据从磁盘读到OS缓存，不涉及用户空间
    tcp_nopush on; # sendfile开启下，提高网络包的传输效率。
#    tcp_nodelay on; # keeyalive连接下，提高网络包传输的实时性。

    # 获取真实ip
    set_real_ip_from 100.0.0.0/8;
    real_ip_header X-Forwarded-For;

    # 上传限制
    client_max_body_size 100m;

#    gzip on;
#    gzip_min_length 1k; # 大于1K的才压缩
#    gzip_buffers 4 16k;
#    gzip_comp_level 4; # 压缩级别，1-10
#    gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css application/json; # 图片不压缩
#    gzip_vary off; # 是否添加“Vary: Accept-Encoding”响应头
#    gzip_disable "MSIE [1-6]\."; # 忽略IE6
#    gzip_http_version 1.1;
#
    proxy_connect_timeout 10s;
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    proxy_set_header host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;

    client_header_buffer_size 512k;
    client_body_buffer_size 1024k;
    fastcgi_buffer_size 1024k;
    fastcgi_buffers 6 256k;
    fastcgi_busy_buffers_size 1024k;

    server_names_hash_max_size 1024;
    vhost_traffic_status_zone;
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }


    server {
        listen 88;
        server_name _;
        vhost_traffic_status off;
        access_log off;

	location /status {
		vhost_traffic_status_display;
		vhost_traffic_status_display_format html;
        }

        location = /upstream_status {
            check_status;
        }
    }

    include conf.d/*.conf;

}
