- name: 添加EPEL仓库
  yum: name=epel-release state=latest

- name: yum public key
  shell: rpm --import http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7

- name: 安装基础软件包
  yum: 
    name: 
      - jq
      - bash-completion
      - rsync
      - mlocate
      - strace
      - htop
      - tar
      - lsof
      - ngrep
      - nmap
      - screen
      - wget
      - nload
      - iftop
      - iotop
      - telnet
      - ntpdate
      - unzip
      - lrzsz
      - cloud-utils-growpart
      - xfsprogs
      - bind-utils
      - deltarpm
    state: latest

