- import_tasks: centos-common.yml
  when: ansible_distribution == "CentOS"

- name: sync init.d
  synchronize:
    src: "{{ item }}"
    dest: "{{ INIT_D_PATH }}"
    owner: true
    group: true
    recursive: yes
  with_items:
  - "init.d/"

- name: add /etc/rc.local
  lineinfile: dest=/etc/rc.local line="bash {{ INIT_D_PATH }}/system-init.sh"

- name: chmod +x /etc/rc.local
  shell: chmod +x /etc/rc.d/rc.local

- name: ntpdate for reboot
  cron: name="ntpdate for reboot" special_time="reboot" job="/usr/sbin/ntpdate ntp1.aliyun.com"

- name: add ntpdate time
  cron: name="update time" hour="*/6" job="/usr/sbin/ntpdate ntp1.aliyun.com"

