- name: sync mid script
  template:
    src: "{{ item }}"
    dest: "{{ REMOTE_PATH }}/{{ item }}"
  with_items:
  - "jaeger/jaeger-agent.service"

- name: add jaeger-agent.service
  shell: mv "{{ REMOTE_PATH }}/{{ item }}" /etc/systemd/system/jaeger-agent.service
  with_items:
  - "jaeger/jaeger-agent.service"

- name: restart jaeger-agent
  service:
    name: jaeger-agent
    state: restarted
    enabled: true
